name: 'publish'

on:
  push:
    tags:
      - '*' # Only run on tag pushes.

env:
  APP_NAME: "Chamber"

jobs:
  publish-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # if: startsWith(github.ref, 'refs/tags/v') 
    # Added a condition to ensure the workflow runs only for tags starting with 'v'
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17' # Updated to Java 17 to fix the sdkmanager error.

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;27.0.11902837"

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: install frontend dependencies
        run: pnpm install

      - name: setup Android signing
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_RELEASE_KEY }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_RELEASE_PASSWORD }}" >> keystore.properties
          # Save the secret to a temporary file
          echo "${{ secrets.ANDROID_RELEASE_KEYSTORE }}" > $RUNNER_TEMP/upload-keystore.txt
          # Decode the file using your preferred command
          base64 --decode $RUNNER_TEMP/upload-keystore.txt > $RUNNER_TEMP/upload-keystore.jks
          echo "storeFile=$RUNNER_TEMP/upload-keystore.jks" >> keystore.properties

      - name: Verify keystore decoding
        run: |
          ls -lh $RUNNER_TEMP
          file $RUNNER_TEMP/upload-keystore.jks

      - name: Build app bundle
        run: pnpm tauri android build -v
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/27.0.11902837

      - name: Get Node project version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Rename APK file
        run: |
          mv ./src-tauri/gen/android/app/build/outputs/apk/release/app-release.apk ./src-tauri/gen/android/app/build/outputs/apk/release/${{ env.APP_NAME }}-${{ steps.package-version.outputs.current-version}}.apk

      - name: Build Android App Bundle
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "${{ env.APP_NAME }} v__VERSION__"
          draft: true
          prerelease: false
          files: |
            ./src-tauri/gen/android/app/build/outputs/apk/release/${{ env.APP_NAME }}-${{ steps.package-version.outputs.current-version}}.apk
